services:
  app:
    image: kaiquebt/scrip:latest
    container_name: scrip
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      SCRIP_HOST: 0.0.0.0
      SCRIP_PORT: 8081
      SCRIP_DATABASE_PATH: data/scrip.sqlite
      SCRIP_JWT_SIGNING_SECRET: change-me
      API_BASE_URL: http://localhost:8081
    volumes:
      - scrip-data:/app/backend/data
    restart: unless-stopped

volumes:
  scrip-data:
